- app/models/item.rb
- app/models/outfit.rb
- app/models/user.rb
Added associations for all the models
> Add associations

- .gitignore
- Gemfile
- Gemfile.lock
- app/models/item.rb
- app/models/outfit.rb
- config/environments/development.rb
- config/environments/production.rb
- config/storage.yml
- db/migrate/20220228145952_create_active_storage_tables.active_storage.rb
- db/schema.rb
Added cloudinary config
Added photo atachment to item
Added photo atachment to outfit
> Add cloudinary

- app/models/user.rb
I forgot about the user  model, so I've just added the attachment
> Added photo attached to user model

- app/controllers/application_controller.rb
- app/views/layouts/application.html.erb
PLEASE update your masters
Yield was missing on the layout, as well as the navbar and everything else
> Added yield for layout

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_outfit_card.scss
- app/views/layouts/application.html.erb
- app/views/shared/_outfit_card.html.erb
> Made the outfit card with placeholders

- app/views/layouts/application.html.erb
- app/views/pages/feed.html.erb
- app/views/shared/_navbar.html.erb
Merged master
Added links to buttons
> Add link create items and outfits

- app/views/shared/_outfit_card.html.erb
> Added the helper to show time ago

- app/controllers/items_controller.rb
- app/controllers/orders_controller.rb
- app/views/items/show.html.erb
- config/routes.rb
in the item show page you can make an offer
> make an offer to a desired item

- app/controllers/outfits_controller.rb
Now you don't get errors if you create an outfit without items
> Added guard clause to create item_outfit

- db/migrate/20220303111408_change_status_to_orders.rb
- db/schema.rb
Now all new orders have a status of pending
> Added default pending to new orders

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_item_card.scss
- app/views/items/show.html.erb
We can select one item's photo.
When the photo clicked it has border and thick.
We will update frontend anyway.
> displaying item with photo on the form

- app/assets/stylesheets/components/_item_card.scss
- app/controllers/outfits_controller.rb
- app/views/outfits/new.html.erb
> item displayed as photos on outfit form

- app/views/items/show.html.erb
- config/initializers/simple_form.rb
When you make an offer, the form doesn't let you submit without choosing your item.
> Fix order bug

- db/seeds.rb
I have two pending orders, a bunch of items and some outfits
> Added myself with some default orders and items

- db/seeds.rb
Now it should show the correct items in the default orders
> Fixed the items from the orders

- app/models/user.rb
Now email must be unique
Now nickname must be unique
> Made email and nickname unique

- app/controllers/pages_controller.rb
- app/views/items/show.html.erb
- app/views/pages/dashboard.html.erb
- app/views/pages/feed.html.erb
- app/views/shared/_full_item_card.html.erb
- app/views/shared/_navbar.html.erb
- app/views/shared/_order_card.html.erb
- app/views/shared/_outfit_card.html.erb
- app/views/shared/_user_info.html.erb
- config/routes.rb
Created the route and updated controller
Created user_info partial
Updated links on all the pages
Updated navbar link
Updated current_user dashboard so it shows only there the sign out button
> Visit other people dashboards

- app/controllers/pages_controller.rb
Now people can visit other people's dashboards without logging in
> Whitelist dashboard from devise

- app/channels/chatroom_channel.rb
- app/controllers/chatrooms_controller.rb
- app/controllers/messages_controller.rb
- app/controllers/orders_controller.rb
- app/javascript/controllers/chatroom_subscription_controller.js
- app/models/chatroom.rb
- app/models/message.rb
- app/models/order.rb
- app/views/chatrooms/show.html.erb
- app/views/messages/_message.html.erb
- app/views/shared/_order_card.html.erb
- config/routes.rb
- db/migrate/20220307100426_create_chatrooms.rb
- db/migrate/20220307100529_create_messages.rb
- db/schema.rb
- test/channels/chatroom_channel_test.rb
- test/controllers/chatrooms_controller_test.rb
- test/controllers/messages_controller_test.rb
- test/models/chatroom_test.rb
- test/models/message_test.rb
> Private chat

- app/controllers/chatrooms_controller.rb
- app/controllers/messages_controller.rb
- app/views/chatrooms/index.html.erb
- app/views/messages/_message.html.erb
- app/views/shared/_navbar.html.erb
- config/routes.rb
- Inbox page created
- User can see with their messages for the specific items
- No design is implemented
> inbox page

- Gemfile
Deleted 'dotenv-rails' because it was duplicated
> Deleted duplicated gem

- app/assets/stylesheets/components/_choose_card.scss
- app/views/shared/_navbar.html.erb
> Updated modal for choose between item and outfit

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_item_card.scss
- app/assets/stylesheets/components/_modal.scss
- app/views/outfits/show.html.erb
- app/views/shared/_item_card.html.erb
- app/views/shared/_outfit_card.html.erb
> Modal for items and showpage for outfit

- app/views/shared/_item_card.html.erb
> Fixed the links, also centered the text

- app/views/items/show.html.erb
item details not displayed if there is no
> item details not displayed if there is no infos

- config/environments/production.rb
> Added line in production config

- app/models/item.rb
Description required when user create an item
> Validation added to item model

- app/assets/stylesheets/application.scss
> Changed link colors in action buttons

- app/controllers/application_controller.rb
- app/helpers/meta_tags_helper.rb
- app/views/items/show.html.erb
- app/views/layouts/application.html.erb
- config/initializers/default_meta.rb
- config/meta.yml
the logo needs to be uploaded in VS Studio Code /app/assets/images
The name of the image should be: **logo.png**
> Title tag is set and exceeds 20 chars

- app/assets/stylesheets/components/_navbar.scss
The logo wasn't loading in production
> Fixed the link of the image so it works in production

- app/assets/config/manifest.json
- app/assets/config/manifest.json.erb
- app/views/layouts/application.html.erb
> Fix manifest

- app/assets/config/manifest.json.erb
- public/manifest.json
Now it should load the manifest correctly
> Moved the manifest to public, made the icons by hand

- public/404.html
- public/500.html
> the width of the container adjusted

- app/assets/stylesheets/components/_item_card.scss
- app/views/items/show.html.erb
> Changed column sizes and changed the class of the outfit images

- app/views/shared/_navbar.html.erb
- public/manifest.json
Hidden the + button for not logged in users
Set minimal ui to the Progressive WebApp settings
> Hidden btn for not logged in users; set minimal-ui to the pwa

- public/manifest.json
> Changed from minimal-ui to standalone

- app/assets/stylesheets/pages/_chatroom_messages.scss
- app/views/chatrooms/show.html.erb
> messages showpage design updated

- app/views/pages/trades.html.erb
Now the link goes to the root instead of create outfit
> Fixed explore cool outfits in the trades page

- app/views/chatrooms/index.html.erb
- app/views/chatrooms/show.html.erb
- app/views/items/show.html.erb
Now the user shouldn't see the make an offer btn if the item is theirs
Fixed go back button in chatrooms and item showpage
> It doesn't show make offer btn if item is yours
